### ISSUE TITLE
[Bug] Transaction processor timeout exception

### ISSUE THREAD

**Issue by pgobin** [hyperledger/sawtooth-next-directory#1082]
Bug | Transaction processor exception
----------|----------
Expected behavior | Expected no exceptions in `rbac-tp` when creating proposal.
Actual behavior | Encountered exception.
Repro steps | Occurred while sequentially creating proposals in the client.
Build | which build number exhibits the issue?
Severity | 2
Details/Notes |
```
rbac-tp                | ERROR:rbac.processor.event_handler:Unexpected processor <class 'TypeError'> exception
rbac-tp                | Traceback (most recent call last):
rbac-tp                |   File "./rbac/common/sawtooth/state_client.py", line 58, in get_addresses
rbac-tp                |     return list(context.get_state(addresses=addresses, timeout=TIMEOUT_SECONDS))
rbac-tp                |   File "/usr/local/lib/python3.5/site-packages/sawtooth_sdk/processor/context.py", line 59, in get_state
rbac-tp                |     request.SerializeToString()).result(timeout).content
rbac-tp                |   File "/usr/local/lib/python3.5/site-packages/sawtooth_sdk/messaging/future.py", line 57, in result
rbac-tp                |     raise FutureTimeoutError('Future timed out')
rbac-tp                | sawtooth_sdk.messaging.future.FutureTimeoutError: Future timed out
rbac-tp                |
rbac-tp                | During handling of the above exception, another exception occurred:
rbac-tp                |
rbac-tp                | Traceback (most recent call last):
rbac-tp                |   File "./rbac/processor/event_handler.py", line 58, in apply
rbac-tp                |     header=transaction.header, payload=payload, context=state
rbac-tp                |   File "./rbac/common/base/base_processor.py", line 114, in handle_message
rbac-tp                |     return handle_message(header, payload, context)
rbac-tp                |   File "./rbac/common/base/base_processor.py", line 64, in handle_message
rbac-tp                |     header=header, payload=payload, context=context
rbac-tp                |   File "./rbac/common/base/base_message.py", line 617, in apply
rbac-tp                |     input_state = self.get_addresses(context=context, addresses=payload.inputs)
rbac-tp                |   File "./rbac/common/base/base_message.py", line 460, in get_addresses
rbac-tp                |     records = state_client.get_addresses(context=context, addresses=addresses)
rbac-tp                |   File "./rbac/common/sawtooth/state_client.py", line 60, in get_addresses
rbac-tp                |     raise InternalError(ERROR_MESSAGE_TIMEOUT, TIMEOUT_SECONDS)
rbac-tp                |   File "/usr/local/lib/python3.5/site-packages/sawtooth_sdk/processor/exceptions.py", line 30, in __init__
rbac-tp                |     raise TypeError("extended_data must be byte-encoded")
rbac-tp                | TypeError: extended_data must be byte-encoded
rbac-tp                | [2019-01-25 01:25:37.731 ERROR    event_handler] Unexpected processor <class 'TypeError'> exception
```

**Comment by PatrickLammers** [comment]
migrated to new tmobile/sawtooth-next-directory repo
